# cocotb Makefile for ddr3_phy_rdlvl FSM.

SIM           ?= icarus
TOPLEVEL_LANG ?= verilog
TOPLEVEL      ?= ddr3_phy_rdlvl
MODULE        ?= test_ddr3_phy_rdlvl

COCOTB_RESULTS_FILE ?= results_rdlvl.xml
SIM_BUILD           ?= sim_build_rdlvl

VERILOG_INCLUDE_DIRS = ../rtl
VERILOG_SOURCES = ../rtl/ddr3_phy_rdlvl.v

COMPILE_ARGS += -g2012 -DBONETTO_SOC_SIM

include $(shell cocotb-config --makefiles)/Makefile.sim
