SIM           ?= icarus
TOPLEVEL_LANG ?= verilog
TOPLEVEL      ?= wb_memory
MODULE        ?= test_wb_memory

VERILOG_SOURCES = ../rtl/wb_memory.v
COMPILE_ARGS    += -g2012

include $(shell cocotb-config --makefiles)/Makefile.sim
