# cocotb Makefile for wb_decode2.

SIM           ?= icarus
TOPLEVEL_LANG ?= verilog
TOPLEVEL      ?= wb_decode2
MODULE        ?= test_wb_decode2

VERILOG_SOURCES = ../rtl/wb_decode2.v
COMPILE_ARGS    += -g2012

include $(shell cocotb-config --makefiles)/Makefile.sim
